// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func About() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"bg-stone-100 shadow-lg rounded-lg p-10 max-w-4xl mx-auto my-12\"><h1 class=\"text-6xl text-slate-700 font-extrabold mb-8 leading-tight\">About</h1><p class=\"text-2xl text-slate-600 leading-relaxed mb-6\">This project demonstrates an auction website built with Golang, Templ, TailwindCSS, and HTMX. Golang powers the backend for performance and scalability, while Templ handles template rendering. TailwindCSS provides responsive styling, and HTMX enhances interactivity without needing a full JavaScript framework. Users can participate in auctions, manage profiles, and interact with a backend that supports authentication and data management using PostgreSQL.</p><p class=\"text-2xl text-slate-600 leading-relaxed\">The site offers a smooth user experience with real-time updates and dynamic content. It's a practical example of a full-stack application, useful for developers and businesses alike. Explore the code and features to see how these technologies come together in this project.</p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
